apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: WtGjVk-nk
    url: http://tasks.prometheus:9090
    version: 1
    isDefault: true
    editable: false
