---

- name: run setup to create root CA, signing cert, and copy cert to host
  include_tasks: setup.yml
  when: tls_ca_setup is defined and tls_ca_setup|bool

- name: create server auth cert
  include_tasks: create_server_cert.yml
  when: tls_server_name is defined

- name: create client auth cert and upload to docker secrets
  include_tasks: create_client_cert.yml
  when: tls_client_name is defined
