---

- name: configure util hosts
  become: true
  hosts: util
  roles:
    - { role: docker, tags: "docker" }
    - { role: docker-compose, tags: "docker-compose" }
    - { role: cadvisor-docker, tags: "cadvisor-docker" }
    - { role: electrumx-docker, tags: "electrumx-docker" }
    - { role: mempool-docker, tags: "mempool-docker" }
    - { role: node_exporter, tags: "node_exporter" }
