---

- name: Create prometheus directory
  file:
    path: /etc/prometheus
    state: directory

- name: Deploy prometheus config
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
  register: prom_config

- name: Create prometheus volume
  community.docker.docker_volume:
    name: prometheus

- name: Deploy prometheus container
  community.docker.docker_container:
    name: prometheus
    image: "prom/prometheus"
    restart_policy: always
    volumes:
      - prometheus:/prometheus
      - /etc/prometheus:/etc/prometheus:ro
    ports:
      - 9090:9090

- name: Reload prometheus container if config changes
  community.docker.docker_container:
    name: prometheus
    state: stopped
    force_kill : true
    kill_signal: SIGHUP
  when: prom_config.changed
